### ISSUE TITLE
angular-sipml in angular 4

### ISSUE THREAD

**Issue by freemanpolys** [SeanHub/angular-sipml#1]
I'd like to use your service but I don't know how to enable it in Angular 4.

**Comment by SeanHub** [comment]
Hi,

Instead of exporting the SIPML service (visible in the extract below)
[https://github.com/SeanHub/angular-sipml/blob/3ed3b02713bccad673db5732d735d8c7da133dab/sm.sipml.ts#L252](https://github.com/SeanHub/angular-sipml/blob/3ed3b02713bccad673db5732d735d8c7da133dab/sm.sipml.ts#L252)

You would export the class as an injectable service adding the following code to the top of the service:

`import { Injectable } from '@angular/core';`

`@Injectable()`

You could use the SIPML service by importing it into your controller like so:

`import { SIPMLService } from '../sm.sipml';`

**Comment by freemanpolys** [comment]
Thanks. I've make sm.sipml injectable and it's working but now I'm having this error in the console :
**ERROR Error: Uncaught (in promise): ReferenceError: tsk_utils_log_set_level is not defined**
Do have an idea on how to solve it ?

**Comment by SeanHub** [comment]
I'm currently using this service with SIPML 2.1.3 so I'd double check that you are using that version.

Try removing the following line:

[https://github.com/SeanHub/angular-sipml/blob/3ed3b02713bccad673db5732d735d8c7da133dab/sm.sipml.ts#L43](https://github.com/SeanHub/angular-sipml/blob/3ed3b02713bccad673db5732d735d8c7da133dab/sm.sipml.ts#L43)

I believe that function calls 'tsk_utils_log_set_level'. I have not seen this error though so can't be sure.

**Comment by freemanpolys** [comment]
I'm using the same version. I think that I have problem adding **src** folder containing **tinyMEDIA**  **tinySAK**    **tinySDP**    **tinySIP** folders in webpack.  with which version of angular are you working ? Do you have tips for adding scipts folder to webpack projet ?

**Comment by freemanpolys** [comment]
I've added successfully all the js in the webpack. I'm having this error  now: 

**core.es5.js?de3d:1020 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setDebugLevel' of null
TypeError: Cannot read property 'setDebugLevel' of null
    at new SIPMLService (sm.sipml.ts?753e:45)
    at _createClass (**

I think the following line is returning null : 
`private _SIP_CLIENT = window['SIPml'] || null;`

Here is how I've initialised the sipml client :  

```
import { Component, OnInit } from '@angular/core';
import { SIPMLService } from './sm.sipml';
import {SipCredential} from './sipcredential.model';
@Component({
  selector: 'jhi-sipml-client',
  templateUrl: './sipml-client.component.html',
  styles: []
})
export class SipmlClientComponent implements OnInit {
    private credential: SipCredential;

  constructor(private sIPMLService: SIPMLService) { }

  ngOnInit() {
       this.credential = new SipCredential() ;
       this.credential.impi = 'test';
       this.credential.impu = 'sip:test@sip2sip.info';
       this.credential.password = 'test';
       this.credential.realm = 'sip2sip.info';
      this.sIPMLService.init(this.credential).then((result) => {
          console.log('---- tryinnnng to connnecccctt --- ' + result);
      });
  }

}

```

**Comment by SeanHub** [comment]
Try entering `window['SIPml']` in a console once your application has fully loaded. If it returns null then your SIPML library has either not been added properly or there is an error in your application which prevents it from being loaded. If it does not return null, it would indicate a race condition, in this scenario I'd presume you're calling `this.sIPMLService.init` before the SIPML library has been loaded.

**Comment by freemanpolys** [comment]
Thanks to your suggestion, window['SIPml'] in the console show me an object
now.
I've resolve the null issue by importing the SIMPL file in *vendor.ts *in
addition to fact that I've copy all the js in the webpack projet already.

I have a new error now  :

core.es5.js?de3d:1020 ERROR Error: Uncaught (in promise): Unauthorized
    at resolvePromise (zone.js?6524:784)
    at eval (zone.js?6524:710)
    at SIPml.Session.Registration.listener (sm.sipml.ts?753e:113)
    at SIPml.Session.Registration.SIPml.EventTarget.dispatchEvent (SIPml.js?svn=251:584)
    at tsip_stack.o_stack.on_event_dialog (SIPml.js?svn=251:880)
    at tsip_event.js?svn=251:123
    at ZoneDelegate.invokeTask (zone.js?6524:424)
    at Object.onInvokeTask (core.es5.js?de3d:3881)
    at ZoneDelegate.invokeTask (zone.js?6524:423)
    at Zone.runTask (zone.js?6524:191)

As a reminder, I'm trying to add the SIPML client in an angular 4 project
generate with Jhipster.

Regards,

**Comment by SeanHub** [comment]
Closing this issue. Last comment is unrelated to this project.
